[metadata]
name = Magistrala
version = 0.0.1
author = Magistrala Contributors
author_email = info@magistrala.com
description = Python SDK for Magistrala
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/absmach/supermq-sdk-py
classifiers =
    Programming Language :: Python :: 3.8.5
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.6
include_package_data = True
