import requests

from magistrala import response
from magistrala import errors
from magistrala import utils


class Alarms:
    """Alarms API client.

    Manages alarms generated by the Rules Engine within a domain.
    """

    ALARMS_ENDPOINT = "alarms"

    def __init__(self, url: str):
        self.URL = url

    def list(self, domain_id: str, query_params: dict, token: str):
        """Lists alarms within a domain.

        params:
            domain_id: str - domain ID
            query_params: dict - pagination/filter params
            token: str - authorization token

        returns:
            mf_resp: response.Response - response object with AlarmsPage
        """
        mf_resp = response.Response()
        http_resp = requests.get(
            self.URL + "/" + domain_id + "/" + self.ALARMS_ENDPOINT,
            headers=utils.construct_header(token, utils.CTJSON),
            params=query_params,
        )
        if http_resp.status_code != 200:
            mf_resp.error.status = 1
            mf_resp.error.message = errors.handle_error(
                errors.alarms["list"], http_resp.status_code
            )
        else:
            mf_resp.value = http_resp.json()
        return mf_resp

    def view(self, domain_id: str, alarm_id: str, token: str):
        mf_resp = response.Response()
        http_resp = requests.get(
            self.URL + "/" + domain_id + "/" + self.ALARMS_ENDPOINT + "/" + alarm_id,
            headers=utils.construct_header(token, utils.CTJSON),
        )
        if http_resp.status_code != 200:
            mf_resp.error.status = 1
            mf_resp.error.message = errors.handle_error(
                errors.alarms["view"], http_resp.status_code
            )
        else:
            mf_resp.value = http_resp.json()
        return mf_resp

    def update(self, domain_id: str, alarm: dict, token: str):
        mf_resp = response.Response()
        http_resp = requests.put(
            self.URL
            + "/"
            + domain_id
            + "/"
            + self.ALARMS_ENDPOINT
            + "/"
            + alarm["id"],
            headers=utils.construct_header(token, utils.CTJSON),
            json=alarm,
        )
        if http_resp.status_code != 200:
            mf_resp.error.status = 1
            mf_resp.error.message = errors.handle_error(
                errors.alarms["update"], http_resp.status_code
            )
        else:
            mf_resp.value = http_resp.json()
        return mf_resp

    def delete(self, domain_id: str, alarm_id: str, token: str):
        mf_resp = response.Response()
        http_resp = requests.delete(
            self.URL + "/" + domain_id + "/" + self.ALARMS_ENDPOINT + "/" + alarm_id,
            headers=utils.construct_header(token, utils.CTJSON),
        )
        if http_resp.status_code != 204:
            mf_resp.error.status = 1
            mf_resp.error.message = errors.handle_error(
                errors.alarms["delete"], http_resp.status_code
            )
        else:
            mf_resp.value = "Alarm deleted successfully"
        return mf_resp
